/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ServiceManager;
import java.awt.Color;
import java.awt.Graphics;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.DuAn;

/**
 *
 * @author macbookpro
 */
public class FormView extends javax.swing.JFrame {

    private DefaultTableModel tableModel;
    private ServiceManager service = new ServiceManager();
    private String path = "duan.txt";
    private DuAn object;

    /**
     * Creates new form FormView
     */
    public FormView() {
        initComponents();
        initComboBox();
        threadClock(this.timeTv);
    }

    public void initComboBox() {
        String[] cols = new String[]{
            "CNTT",
            "Thiết Kế Đồ Họa",
            "Ứng Dụng Phần Mềm",
            "Sales"
        };
        DefaultComboBoxModel<String> boxModel = new DefaultComboBoxModel<>(cols);
        this.cbChuyenNganhf.setModel(boxModel);
    }

    public void initTable() {
        tableModel = (DefaultTableModel) this.tableData.getModel();
        String[] cols = new String[]{
            "Chuyên Ngành",
            "Mã Đề Tài",
            "Tên Đề Tài",
            "Ngày Thực HIện"};
        this.tableModel.setColumnIdentifiers(cols);
    }

    public void fillTable() {
        ArrayList<DuAn> list = this.service.select();
        while (tableModel.getRowCount() > 0) {
            tableModel.removeRow(0);
        }
        for (DuAn object : list) {
            tableModel.addRow(new String[]{
                object.getChuyenNganh(),
                object.getMaDeTai(),
                object.getTenDeThi(),
                object.getNgayThucHien()});
        }

        tableModel.fireTableDataChanged();
    }

    public void threadClock(JLabel jLabel) {
        new Thread(new Runnable() {
            @Override
            public void run() {
                SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss aa");

                while (true) {

                    Date date = new Date();
                    String timeStr = sdf.format(date);

                    jLabel.setText(timeStr);

                    try {
                        Thread.sleep(1000);
                    } catch (Exception e) {
                        System.out.println(" " + e.getMessage());
                    }
                }
            }
        }).start();

    }

    public DuAn inputData() {
        String chuyenNganh = (String) this.cbChuyenNganhf.getSelectedItem();
        String maDetai = inputMa.getText();
        String tenDeTai = inputTen.getText();
        String date = inputDate.getText();

        if (maDetai.isEmpty()) {
            inputMa.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "Not Null");
            return null;
        } else {

            inputMa.setBackground(Color.white);
        }

        if (tenDeTai.isEmpty()) {
            inputTen.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "Not Null");
            return null;
        } else {

            inputTen.setBackground(Color.white);
        }

        if (date.isEmpty()) {
            inputDate.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "Not Null");
            return null;

        }
        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            dateFormat.setLenient(false); //  linh hoạt trong việc phân tích ngày tháng

            Date parsedDate = dateFormat.parse(date);
            object = new DuAn(chuyenNganh, maDetai, tenDeTai, String.valueOf(parsedDate));
            return object;
        } catch (ParseException e) {
            inputDate.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "Vui Lòng Nhập Đúng Định Dạng Ngày dd/MM/yyyy.");
            return null;
        }

    }

    @Override
    public Graphics getGraphics() {
        return super.getGraphics(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        timeTv = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbChuyenNganhf = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        inputMa = new javax.swing.JTextField();
        inputTen = new javax.swing.JTextField();
        inputDate = new javax.swing.JTextField();
        themBtn = new javax.swing.JButton();
        xoaBtn = new javax.swing.JButton();
        moFIleBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        ghiFileBtn = new javax.swing.JButton();
        sapxepBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Quản Lý Đề Tài NCKH");

        timeTv.setText("12:02 am");

        jLabel3.setText("Chuyên Ngành");

        cbChuyenNganhf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Mã Đề Tài");

        jLabel5.setText("Tên Đề Tài");

        jLabel6.setText("Ngày Thực Hiện");

        themBtn.setText("Thêm");
        themBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themBtnActionPerformed(evt);
            }
        });

        xoaBtn.setText("Xóa");
        xoaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaBtnActionPerformed(evt);
            }
        });

        moFIleBtn.setText("Mở File");
        moFIleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moFIleBtnActionPerformed(evt);
            }
        });

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        ghiFileBtn.setText("Ghi FIle");
        ghiFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ghiFileBtnActionPerformed(evt);
            }
        });

        sapxepBtn.setBackground(new java.awt.Color(255, 0, 0));
        sapxepBtn.setForeground(new java.awt.Color(255, 255, 255));
        sapxepBtn.setText("Sắp xếp theo tên");
        sapxepBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sapxepBtnActionPerformed(evt);
            }
        });

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbChuyenNganhf, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(inputDate, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputTen, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputMa))
                                .addGap(214, 214, 214))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(95, 95, 95))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ghiFileBtn)
                                    .addComponent(themBtn)
                                    .addComponent(timeTv)
                                    .addComponent(xoaBtn)
                                    .addComponent(moFIleBtn)
                                    .addComponent(resetBtn)))
                            .addComponent(sapxepBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(timeTv))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbChuyenNganhf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(themBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inputMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(xoaBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inputTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(inputDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(resetBtn)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(ghiFileBtn)
                        .addGap(34, 34, 34)
                        .addComponent(moFIleBtn)
                        .addGap(35, 35, 35)
                        .addComponent(sapxepBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void themBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themBtnActionPerformed
        object = this.inputData();
        if (object == null) {
            return;
        }
        this.service.insert(object);
        fillTable();
        this.resetBtnActionPerformed(evt);
        JOptionPane.showMessageDialog(this, "Successfully");
// TODO add your handling code here:
    }//GEN-LAST:event_themBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        initTable();
        fillTable();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void xoaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaBtnActionPerformed
        int postion = this.tableData.getSelectedRow();
        if (postion == -1) {
            JOptionPane.showMessageDialog(this, "Hãy chọn 1 dòng trong bảng để Xóa");
            return;

        }
        this.service.delete(postion);
        fillTable();
        this.resetBtnActionPerformed(evt);
        JOptionPane.showMessageDialog(this, "Successfully");

// TODO add your handling code here:
    }//GEN-LAST:event_xoaBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        inputMa.setText(null);
        inputTen.setText(null);
        inputDate.setText(null);// TODO add your handling code here:
    }//GEN-LAST:event_resetBtnActionPerformed

    private void ghiFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ghiFileBtnActionPerformed
        this.service.writeFile(path);
        JOptionPane.showMessageDialog(this, "Ghi File Thành Công !");// TODO add your handling code here:
    }//GEN-LAST:event_ghiFileBtnActionPerformed

    private void moFIleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moFIleBtnActionPerformed
        this.service.readFile(path);
        fillTable();
        JOptionPane.showMessageDialog(this, "Đọc File Thành Công !");// TODO add your handling code here:
// TODO add your handling code here:
    }//GEN-LAST:event_moFIleBtnActionPerformed

    private void tableDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDataMouseClicked
        int row = tableData.getSelectedRow();
        if (row == -1) {
            return;
        }
        String chuyenNganh = this.tableData.getValueAt(row, 0).toString();
        String maDetai = this.tableData.getValueAt(row, 1).toString();
        String tenDetai = this.tableData.getValueAt(row, 2).toString();
        String date = this.tableData.getValueAt(row, 3).toString();

        //fomart String date -> date 
        //set data to ui
        this.cbChuyenNganhf.setSelectedItem(chuyenNganh);
        this.inputMa.setText(maDetai);
        this.inputTen.setText(tenDetai);
        this.inputDate.setText(date);
    }//GEN-LAST:event_tableDataMouseClicked

    private void sapxepBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sapxepBtnActionPerformed
        this.service.sortByName();
        fillTable();
        JOptionPane.showMessageDialog(this, "Sắp Xếp Thành Công");// TODO add your handling code here:
    }//GEN-LAST:event_sapxepBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbChuyenNganhf;
    private javax.swing.JButton ghiFileBtn;
    private javax.swing.JTextField inputDate;
    private javax.swing.JTextField inputMa;
    private javax.swing.JTextField inputTen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton moFIleBtn;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton sapxepBtn;
    private javax.swing.JTable tableData;
    private javax.swing.JButton themBtn;
    private javax.swing.JLabel timeTv;
    private javax.swing.JButton xoaBtn;
    // End of variables declaration//GEN-END:variables
}
