/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop;

import b2.DienThoaiService;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author minhs
 */
public class QuanLyDienThoai extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyDienThoai
     */
    public QuanLyDienThoai() {
        initComponents();
        dsdt.add(new DienThoai("Dt01", "SamSung", "Trắng", "64", 10000));
        dsdt.add(new DienThoai("Dt02", "Apple", "Đen", "128", 1000));
        dsdt.add(new DienThoai("Dt03", "Oppo", "Trắng", "512", 100));
        dsdt.add(new DienThoai("Dt04", "Oppo", "Vàng", "64", 10));
        dsdt.add(new DienThoai("Dt05", "SamSung", "Trắng", "256", 1));
        cb();
        first();
        loadTable();
    }
    List<DienThoai> dsdt = new ArrayList<>();
    DienThoai dtt;
    DefaultComboBoxModel<DienThoai> model = new DefaultComboBoxModel<>();
    DefaultTableModel model_table;
    DienThoaiService service = new DienThoaiService();
    int index = -1;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void loadTable() {
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnCount(0);
        //model.addColumn("STT");
        model.addColumn("Mã");
        model.addColumn("Hãng");
        model.addColumn("Màu Sắc");
        model.addColumn("Bộ Nhớ");
        model.addColumn("Giá");
        model.addColumn("Trạng Thái");
        tbDienThoai.setModel(model);
        model.setRowCount(0);
        for (DienThoai dt : dsdt) {
            Object[] row = new Object[]{
                dt.getMa(), dt.getHang(), dt.getMauSac(), dt.getBoNho(), dt.getGia(), dt.getStatus()
            };
            model.addRow(row);
        }

    }
//    public void loadTable(List<DienThoai> list) {
//        model_table = (DefaultTableModel) tbDienThoai.getModel();
//        model_table.setRowCount(0);
//        for(DienThoai dt:list){
//            model_table.addRow(dt.toDaTa());
//        }
//        
//    }

    public static String genMa() {
        Random random = new Random();
        String str = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()_+";
        StringBuilder sb = new StringBuilder(7);
        for (int i = 0; i < 3; i++) {
            sb.append(str.charAt(random.nextInt(str.length())));
        }
        for (int i = 0; i < 2; i++) {
            sb.append(Character.toLowerCase(str.charAt(random.nextInt(str.length()))));
        }
        sb.append(str.charAt(random.nextInt(str.length())));
        sb.append(random.nextInt(10));
        return sb.toString();
    }

    void first() {
        dtt = dsdt.get(0);
        txtMa.setText(dtt.getMa());
        cbHang.setSelectedItem(dtt.getHang());
        txtBoNho.setText(dtt.getBoNho());
        txtGia.setText(dtt.getGia() + "");
        String color = dtt.getMauSac();
        if (color.equals("Đen")) {
            bt1.setSelected(true);
        } else if (color.equals("Trắng")) {
            bt2.setSelected(true);
        } else {
            bt3.setSelected(true);
        }

    }

    public void cb() {
        DefaultComboBoxModel<String> model1 = new DefaultComboBoxModel<>();
        model1.addElement("Apple");
        model1.addElement("SamSung");
        model1.addElement("Oppo");
        cbHang.setModel(model1);

    }


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMau = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        txtBoNho = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        cbHang = new javax.swing.JComboBox<>();
        btnMo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDienThoai = new javax.swing.JTable();
        bt1 = new javax.swing.JRadioButton();
        bt2 = new javax.swing.JRadioButton();
        bt3 = new javax.swing.JRadioButton();
        btnGhi = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Quản Lý Điện Thoại");

        jLabel2.setText("Mã");

        jLabel3.setText("Hãng");

        jLabel4.setText("Bộ Nhớ ");

        txtMau.setText("Màu Sắc");

        jLabel6.setText("Giá:");

        txtMa.setEditable(false);

        cbHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnMo.setText("Mở File");
        btnMo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoActionPerformed(evt);
            }
        });

        tbDienThoai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "MÃ", "HÃNG", "MÀU", "BỘ NHỚ", "GIÁ", "TRẠNG THÁI"
            }
        ));
        tbDienThoai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDienThoaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDienThoai);

        buttonGroup1.add(bt1);
        bt1.setText("Đen");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(bt2);
        bt2.setText("Trắng");

        buttonGroup1.add(bt3);
        bt3.setText("Vàng");

        btnGhi.setText("Ghi file");
        btnGhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhiActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("GB");

        jButton1.setText("Xoa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMa)
                                    .addComponent(txtBoNho)
                                    .addComponent(cbHang, 0, 93, Short.MAX_VALUE)))
                            .addComponent(btnThem))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton1)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtMau, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(43, 43, 43)
                                                .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(bt2)))
                                        .addGap(18, 18, 18)
                                        .addComponent(bt3))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(btnGhi)
                                .addGap(78, 78, 78)
                                .addComponent(btnMo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMau)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt1)
                    .addComponent(bt2)
                    .addComponent(bt3))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBoNho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jButton1))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnGhi)
                    .addComponent(btnMo))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbDienThoaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDienThoaiMouseClicked
        // TODO add your handling code here:
        int stt = tbDienThoai.getSelectedRow();
        String id = tbDienThoai.getValueAt(stt, 0).toString();
        String bnho = tbDienThoai.getValueAt(stt, 3).toString();
        String gia = tbDienThoai.getValueAt(stt, 4).toString();
        cbHang.setSelectedItem(tbDienThoai.getValueAt(stt, 1).toString());
        String mauSac = tbDienThoai.getValueAt(stt, 2).toString();

        if (mauSac.equals("Đen")) {
            bt1.setSelected(true);
        } else if (mauSac.equals("Trắng")) {
            bt2.setSelected(true);
        } else {
            bt3.setSelected(true);
        }
        txtMa.setText(id);
        txtBoNho.setText(bnho);
        txtGia.setText(gia);


    }//GEN-LAST:event_tbDienThoaiMouseClicked


    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (txtMa.getText().equals("") || cbHang.getSelectedItem().equals("")
                || txtBoNho.getText().equals("") || txtGia.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin");
            return;
        }
        int gia = 0;
        try {
            gia = Integer.parseInt(txtGia.getText());
            if (gia <= 100) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Giá phải là số nguyên dương và lớn hơn 100");
            return;
        }
        String id = txtMa.getText();
        id = genMa();
        for (DienThoai dt : dsdt) {
            if (id.equalsIgnoreCase(dt.getMa())) {
                JOptionPane.showMessageDialog(this, "id đã tồn tại");
                return;
            }
        }
        String hang = (String) cbHang.getSelectedItem();
        String color = "";
        if (bt1.isSelected()) {
            color = "Đen";
        } else if (bt2.isSelected()) {
            color = "Trắng";
        } else if (bt3.isSelected()) {
            color = "Vàng";
        }
        String bnho = txtBoNho.getText();
        int price = Integer.parseInt(txtGia.getText());
        dsdt.add(new DienThoai(id, hang, color, bnho, price));
        txtMa.setText("");
        JOptionPane.showMessageDialog(this, "Thêm thành công");

        loadTable();
    }//GEN-LAST:event_btnThemActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt1ActionPerformed

    private void btnGhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhiActionPerformed
        try {
            FileOutputStream fos = new FileOutputStream("duyy.txt");
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            oos.writeObject(dsdt);
            fos.close();
            oos.close();
            JOptionPane.showMessageDialog(this, "ghi thanh cong");
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(QuanLyDienThoai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnGhiActionPerformed

    private void btnMoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoActionPerformed
        try {
            // TODO add your handling code here:
            loadData();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanLyDienThoai.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadTable();
    }//GEN-LAST:event_btnMoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int index = tbDienThoai.getSelectedRow();
        String id = tbDienThoai.getValueAt(index, 0).toString();
        dsdt.remove(id);
        loadTable();

    }//GEN-LAST:event_jButton1ActionPerformed
    public void loadData() throws ClassNotFoundException {
        try {
            FileInputStream fis = new FileInputStream("duyy.txt");
            ObjectInputStream ois = new ObjectInputStream(fis);
            dsdt = (ArrayList<DienThoai>) ois.readObject();
            fis.close();
            ois.close();
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(QuanLyDienThoai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyDienThoai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyDienThoai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyDienThoai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyDienThoai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyDienThoai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bt1;
    private javax.swing.JRadioButton bt2;
    private javax.swing.JRadioButton bt3;
    private javax.swing.JButton btnGhi;
    private javax.swing.JButton btnMo;
    private javax.swing.JButton btnThem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbHang;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDienThoai;
    private javax.swing.JTextField txtBoNho;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMa;
    private javax.swing.JLabel txtMau;
    // End of variables declaration//GEN-END:variables
}
